<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <WarnOn>3389;3390;3395</WarnOn>
    <OutputPath>..\..\..\bin\$(Configuration)</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Assertions.fs" />
    <Compile Include="Generators.fs" />
    <None Include="paket.references" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\OpenTK\OpenTK.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>